enableTelemetry: false

nodeLinker: node-modules

packageExtensions:
  "@parcel/optimizer-image@*":
    dependencies:
      "@parcel/core": ^2.0.0
  "@parcel/transformer-image@*":
    dependencies:
      "@parcel/core": ^2.0.0
  "@parcel/transformer-js@*":
    dependencies:
      "@parcel/core": ^2.0.0
  "@parcel/transformer-postcss@*":
    dependencies:
      postcss: ^8.0.0
  "@parcel/types@*":
    dependencies:
      "@parcel/core": ^2.0.0
  ts-standard@*:
    dependencies:
      "@typescript-eslint/parser": ^4.0.0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://mskelton.dev/yarn-outdated/v2"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
